language: node_js
dist: trusty
node_js:
  - "stable"
before_install:
  - find /lib /usr -name 'libz.so*' -ls
  - sudo apt-get install -y build-essential nasm zlib1g-dev libpng-dev libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - wget https://zlib.net/zlib-1.2.11.tar.gz && tar -xvzf zlib-1.2.11.tar.gz && cd zlib-1.2.11 && sudo ./configure --prefix=/lib/x86_64-linux-gnu && sudo make install && cd ..
  - find /lib /usr -name 'libz.so*' -ls
script: npm test
